# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a19a4fffb10ba706e2a762f356d36f5fa7f6813bfba411565f13e1a362df014b4f6dabb530985c719ee414f3762493125ba0e5c67b9150607eaa546f5875f5f

test:
  secret_key_base: b7b1ec93c5ce53d47220ddad6b57f36472b6c7cf9340b3d26647f4529da43362efe30999fe811c00730bc2b4842610d67cfc54abf8c7f1afc8b10f6dc1d12c8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
